// Application Configuration Constants
// Update this file when selling to different buyers

export const APP_CONFIG = {
  // Company Information
  COMPANY: {
    NAME: 'Ruhunu Tyre House',
    FULL_NAME: 'RUHUNU TYRE HOUSE - GALNEWA',
    SHORT_NAME: 'Ruhunu Tyre House - IMS',
    LOCATION: 'GALNEWA',
    ICON: '🏢',
    LOGO_URL: null, // Add logo URL when available
  },

  // Contact Information
  CONTACT: {
    PHONE: '077-123-4567',
    EMAIL: 'info@ruhunutyre.lk',
    ADDRESS: 'Main Street, Galnewa, Sri Lanka',
    WEBSITE: 'www.ruhunutyre.lk',
    SUPPORT_PHONE: '077-123-4567',
    SUPPORT_EMAIL: 'support@ruhunutyre.lk',
  },

  // Application Branding
  BRANDING: {
    PRIMARY_COLOR: '#2563eb', // Blue
    SECONDARY_COLOR: '#10b981', // Green
    ACCENT_COLOR: '#f59e0b', // Orange
    ERROR_COLOR: '#ef4444', // Red
    SUCCESS_COLOR: '#10b981', // Green
    WARNING_COLOR: '#f59e0b', // Orange
    INFO_COLOR: '#3b82f6', // Blue
    
    // Theme colors for different sections
    DASHBOARD_COLOR: '#2563eb',
    SALES_COLOR: '#10b981',
    INVENTORY_COLOR: '#8b5cf6',
    REPORTS_COLOR: '#f59e0b',
    SETTINGS_COLOR: '#6b7280',
  },

  // Currency and Formatting
  CURRENCY: {
    SYMBOL: 'Rs.',
    CODE: 'LKR',
    DECIMAL_PLACES: 2,
    THOUSAND_SEPARATOR: ',',
    DECIMAL_SEPARATOR: '.',
  },

  // Print Templates
  PRINT: {
    BILL_TITLE: 'Sales Receipt',
    INVOICE_TITLE: 'Invoice',
    REPORT_TITLE: 'Sales Report',
    FOOTER_TEXT: 'Thank you for your business!',
    TERMS_CONDITIONS: 'Terms and conditions apply. No returns without receipt.',
    COMPANY_SLOGAN: 'Your trusted tyre partner',
  },

  // Business Settings
  BUSINESS: {
    BUSINESS_TYPE: 'Tyre Shop', // Can be changed to 'Retail Store', 'Pharmacy', etc.
    INDUSTRY: 'Automotive',
    TAX_RATE: 0, // Percentage (0-100)
    DEFAULT_DISCOUNT: 0,
    ALLOW_NEGATIVE_STOCK: false,
    REQUIRE_CUSTOMER_INFO: false,
  },

  // Application Features
  FEATURES: {
    ENABLE_BARCODE: true,
    ENABLE_CATEGORIES: true,
    ENABLE_CUSTOMER_MANAGEMENT: true,
    ENABLE_STOCK_ALERTS: true,
    ENABLE_REPORTS: true,
    ENABLE_EMAIL_NOTIFICATIONS: true,
    ENABLE_MULTI_USER: true,
    ENABLE_BACKUP: true,
  },

  // Navigation and UI
  UI: {
    SIDEBAR_TITLE: 'Inventory Management',
    DASHBOARD_TITLE: 'Dashboard',
    DEFAULT_PAGE_SIZE: 10,
    MAX_ITEMS_PER_PAGE: 100,
    SHOW_COMPANY_LOGO: true,
    SHOW_FOOTER: true,
    ENABLE_DARK_MODE: false,
  },

  // Report Templates
  REPORTS: {
    COMPANY_HEADER: true,
    SHOW_LOGO: true,
    GENERATED_BY_TEXT: 'Generated by',
    DATE_FORMAT: 'DD/MM/YYYY',
    TIME_FORMAT: '12', // 12 or 24 hour format
  },

  // Email Configuration
  EMAIL: {
    FROM_NAME: 'Ruhunu Tyre House',
    FROM_EMAIL: 'noreply@ruhunutyre.lk',
    SUPPORT_EMAIL: 'support@ruhunutyre.lk',
    SIGNATURE: 'Best regards,\nRuhunu Tyre House Team',
  },

  // System Information
  SYSTEM: {
    VERSION: '1.0.0',
    LAST_UPDATED: '2024-01-01',
    DEVELOPER: 'Your Development Team',
    SUPPORT_URL: 'https://support.ruhunutyre.lk',
  },

  // Customization for different business types
  TEMPLATES: {
    TYRE_SHOP: {
      ITEM_LABEL: 'Tyre/Product',
      CATEGORY_EXAMPLES: ['Tyres', 'Tubes', 'Accessories', 'Services'],
      UNIT_LABEL: 'Pieces',
    },
    PHARMACY: {
      ITEM_LABEL: 'Medicine/Product',
      CATEGORY_EXAMPLES: ['Medicines', 'Supplements', 'Personal Care', 'Medical Devices'],
      UNIT_LABEL: 'Units',
    },
    RETAIL_STORE: {
      ITEM_LABEL: 'Product',
      CATEGORY_EXAMPLES: ['Electronics', 'Clothing', 'Home & Garden', 'Sports'],
      UNIT_LABEL: 'Items',
    },
    GROCERY: {
      ITEM_LABEL: 'Product',
      CATEGORY_EXAMPLES: ['Vegetables', 'Fruits', 'Dairy', 'Beverages', 'Snacks'],
      UNIT_LABEL: 'Items',
    },
  },
};

// Helper function to get current template
export const getCurrentTemplate = () => {
  const businessType = APP_CONFIG.BUSINESS.BUSINESS_TYPE.toLowerCase().replace(/\s+/g, '_');
  return APP_CONFIG.TEMPLATES[businessType.toUpperCase()] || APP_CONFIG.TEMPLATES.RETAIL_STORE;
};

// Helper function to format currency
export const formatCurrency = (amount) => {
  const { SYMBOL, DECIMAL_PLACES, THOUSAND_SEPARATOR, DECIMAL_SEPARATOR } = APP_CONFIG.CURRENCY;
  
  if (isNaN(amount) || amount === null || amount === undefined) {
    return `${SYMBOL} 0${DECIMAL_SEPARATOR}${'0'.repeat(DECIMAL_PLACES)}`;
  }

  const fixedAmount = parseFloat(amount).toFixed(DECIMAL_PLACES);
  const [integer, decimal] = fixedAmount.split('.');
  
  // Add thousand separators
  const formattedInteger = integer.replace(/\B(?=(\d{3})+(?!\d))/g, THOUSAND_SEPARATOR);
  
  return `${SYMBOL} ${formattedInteger}${DECIMAL_SEPARATOR}${decimal}`;
};

// Helper function to get theme colors
export const getThemeColor = (section) => {
  const colorMap = {
    dashboard: APP_CONFIG.BRANDING.DASHBOARD_COLOR,
    sales: APP_CONFIG.BRANDING.SALES_COLOR,
    inventory: APP_CONFIG.BRANDING.INVENTORY_COLOR,
    reports: APP_CONFIG.BRANDING.REPORTS_COLOR,
    settings: APP_CONFIG.BRANDING.SETTINGS_COLOR,
  };
  
  return colorMap[section] || APP_CONFIG.BRANDING.PRIMARY_COLOR;
};

// Export individual sections for easier imports
export const COMPANY = APP_CONFIG.COMPANY;
export const CONTACT = APP_CONFIG.CONTACT;
export const BRANDING = APP_CONFIG.BRANDING;
export const CURRENCY = APP_CONFIG.CURRENCY;
export const PRINT = APP_CONFIG.PRINT;
export const BUSINESS = APP_CONFIG.BUSINESS;
export const FEATURES = APP_CONFIG.FEATURES;
export const UI = APP_CONFIG.UI;
export const REPORTS = APP_CONFIG.REPORTS;
export const EMAIL = APP_CONFIG.EMAIL;
export const SYSTEM = APP_CONFIG.SYSTEM;

export default APP_CONFIG;
